import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(page_title="Customer Segmentation", page_icon="👥")

st.title("👥 Customer Segmentation Dashboard")
st.markdown("Explore customer personas generated by our unsupervised learning pipelines.")

col1, col2 = st.columns(2)

with col1:
    st.subheader("Cluster Distribution")
    # Placeholder for cluster distribution chart
    chart_data = pd.DataFrame(
        np.random.randn(20, 3),
        columns=['Loyal', 'At-Risk', 'New']
    )
    st.bar_chart(chart_data)

with col2:
    st.subheader("RFM Metrics")
    st.metric("Avg Recency", "12 Days", "-2 Days")
    st.metric("Avg Frequency", "3.4 Purchases", "+0.4")
    st.metric("Avg Monetary Value", "$145.20", "+$12.50")

st.markdown("### Underlying ML Technology")
st.markdown("- **Algorithm**: K-Means & Gaussian Mixture Models (RAPIDS cuML).")
st.markdown("- **Dimensionality Reduction**: GPU-accelerated PCA and t-SNE.")
