import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "id": "intro",
   "metadata": {},
   "source": [
    "# Project 3: Fashion Product Image Categorizer - Step 1: CV Classification Pipeline\n",
    "\n",
    "This notebook implements a classical computer vision pipeline to classify clothing products from the Fashion-MNIST dataset.\n",
    "\n",
    "## Blueprint Actions Covered\n",
    "* **Image Preprocessing**: Normalize pixel values, reshape and downsample/resize images, and flatten back to 1D vectors.\n",
    "* **Dimensionality Reduction**: Apply Principal Component Analysis (PCA) to compress pixel dimensions while retaining variance.\n",
    "* **Classification**: Train and optimize Support Vector Classifier (SVC) and k-Nearest Neighbors (kNN) models to categorize products."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "imports",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import time\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sklearn.model_selection import train_test_split, GridSearchCV\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay, accuracy_score, f1_score\n",
    "import skimage.transform\n",
    "import joblib\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# Paths to Fashion-MNIST CSV dataset files\n",
    "TRAIN_CSV = \"../datasets/fashion-mnist/fashion-mnist_train.csv\"\n",
    "TEST_CSV = \"../datasets/fashion-mnist/fashion-mnist_test.csv\"\n",
    "\n",
    "print(f\"Train file exists: {os.path.exists(TRAIN_CSV)}\")\n",
    "print(f\"Test file exists:  {os.path.exists(TEST_CSV)}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "data_loading_title",
   "metadata": {},
   "source": [
    "## 1. Data Ingestion & Stratified Downsampling\n",
    "\n",
    "We load the Fashion-MNIST CSV files and downsample them to stratified subsets (10,000 train, 2,000 test) to optimize SVM and kNN training times on CPU while ensuring fair class representation."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "data_loading_execution",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Loading raw Fashion-MNIST datasets...\")\n",
    "df_train_raw = pd.read_csv(TRAIN_CSV)\n",
    "df_test_raw = pd.read_csv(TEST_CSV)\n",
    "\n",
    "print(f\"Raw train shape: {df_train_raw.shape}\")\n",
    "print(f\"Raw test shape:  {df_test_raw.shape}\")\n",
    "\n",
    "# Perform stratified downsampling\n",
    "df_train_sampled, _ = train_test_split(\n",
    "    df_train_raw, \n",
    "    train_size=10000, \n",
    "    stratify=df_train_raw['label'], \n",
    "    random_state=42\n",
    ")\n",
    "\n",
    "df_test_sampled, _ = train_test_split(\n",
    "    df_test_raw, \n",
    "    train_size=2000, \n",
    "    stratify=df_test_raw['label'], \n",
    "    random_state=42\n",
    ")\n",
    "\n",
    "# Separate features and labels\n",
    "X_train_raw = df_train_sampled.drop(columns=['label']).values\n",
    "y_train = df_train_sampled['label'].values\n",
    "\n",
    "X_test_raw = df_test_sampled.drop(columns=['label']).values\n",
    "y_test = df_test_sampled['label'].values\n",
    "\n",
    "class_names = [\n",
    "    \"T-shirt/top\", \"Trouser\", \"Pullover\", \"Dress\", \"Coat\", \n",
    "    \"Sandal\", \"Shirt\", \"Sneaker\", \"Bag\", \"Ankle boot\"\n",
    "]\n",
    "\n",
    "print(f\"\\nDownsampled train shape: X = {X_train_raw.shape}, y = {y_train.shape}\")\n",
    "print(f\"Downsampled test shape:  X = {X_test_raw.shape}, y = {y_test.shape}\")\n",
    "print(\"Class distribution in training subset:\", np.bincount(y_train))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "eda_title",
   "metadata": {},
   "source": [
    "## 2. Visual Exploration & EDA\n",
    "\n",
    "We reshape the flat vectors to 2D image matrices and visualize one representative sample for each of the 10 clothing categories."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "eda_execution",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Find first sample of each class\n",
    "sample_indices = [np.where(y_train == i)[0][0] for i in range(10)]\n",
    "\n",
    "fig, axes = plt.subplots(2, 5, figsize=(12, 6))\n",
    "axes = axes.ravel()\n",
    "\n",
    "for idx, class_id in enumerate(range(10)):\n",
    "    sample_idx = sample_indices[class_id]\n",
    "    img = X_train_raw[sample_idx].reshape(28, 28)\n",
    "    \n",
    "    axes[idx].imshow(img, cmap='gray')\n",
    "    axes[idx].set_title(f\"{class_id}: {class_names[class_id]}\", fontsize=10)\n",
    "    axes[idx].axis('off')\n",
    "\n",
    "plt.suptitle(\"Fashion-MNIST: Sample Images from Each Class\", fontsize=14, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "PLOT_DIR = \"plots\"\n",
    "os.makedirs(PLOT_DIR, exist_ok=True)\n",
    "plt.savefig(os.path.join(PLOT_DIR, \"01_sample_class_grid.png\"), dpi=150)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "preprocessing_title",
   "metadata": {},
   "source": [
    "## 3. Image Preprocessing Pipeline\n",
    "\n",
    "We define a processing function that normalizes pixel intensities, reshapes to 2D, resizes to a lower 14x14 resolution (the \"Resize\" blueprint requirement), and flattens back into a 1D vector of length 196."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "preprocessing_execution",
   "metadata": {},
   "outputs": [],
   "source": [
    "def preprocess_images(images, target_size=(14, 14)):\n",
    "    # 1. Normalize pixel values\n",
    "    normalized = images / 255.0\n",
    "    \n",
    "    preprocessed = []\n",
    "    for img_flat in normalized:\n",
    "        # 2. Reshape to 2D image matrix\n",
    "        img_2d = img_flat.reshape(28, 28)\n",
    "        # 3. Resize using anti-aliasing\n",
    "        img_resized = skimage.transform.resize(img_2d, target_size, anti_aliasing=True)\n",
    "        # 4. Flatten back to 1D\n",
    "        preprocessed.append(img_resized.flatten())\n",
    "        \n",
    "    return np.array(preprocessed)\n",
    "\n",
    "print(\"Preprocessing training and test images...\")\n",
    "X_train_preprocessed = preprocess_images(X_train_raw)\n",
    "X_test_preprocessed = preprocess_images(X_test_raw)\n",
    "\n",
    "print(f\"Preprocessed train shape: {X_train_preprocessed.shape}\")\n",
    "print(f\"Preprocessed test shape:  {X_test_preprocessed.shape}\")\n",
    "\n",
    "# Visualize original vs. preprocessed image comparison\n",
    "original_img = (X_train_raw[0] / 255.0).reshape(28, 28)\n",
    "resized_img = X_train_preprocessed[0].reshape(14, 14)\n",
    "\n",
    "fig, axes = plt.subplots(1, 2, figsize=(8, 4))\n",
    "axes[0].imshow(original_img, cmap='gray')\n",
    "axes[0].set_title(f\"Original (28x28)\\nFeatures: 784\", fontsize=11)\n",
    "axes[0].axis('off')\n",
    "\n",
    "axes[1].imshow(resized_img, cmap='gray')\n",
    "axes[1].set_title(f\"Resized (14x14)\\nFeatures: 196\", fontsize=11)\n",
    "axes[1].axis('off')\n",
    "\n",
    "plt.suptitle(f\"Preprocessing Comparison - Class: {class_names[y_train[0]]}\", fontsize=13, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig(os.path.join(PLOT_DIR, \"01_preprocessing_comparison.png\"), dpi=150)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "pca_title",
   "metadata": {},
   "source": [
    "## 4. Dimensionality Reduction (PCA)\n",
    "\n",
    "We fit PCA to identify the minimum number of principal components needed to explain 95% of cumulative variance. We then transform our features and plot a 2D projection along with the visual representations of the principal component weights (\"eigenimages\")."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "pca_execution",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Analyzing PCA explained variance...\")\n",
    "pca_temp = PCA(random_state=42)\n",
    "pca_temp.fit(X_train_preprocessed)\n",
    "\n",
    "# Cumulative explained variance\n",
    "cumulative_variance = np.cumsum(pca_temp.explained_variance_ratio_)\n",
    "n_components_90 = np.argmax(cumulative_variance >= 0.90) + 1\n",
    "n_components_95 = np.argmax(cumulative_variance >= 0.95) + 1\n",
    "\n",
    "plt.figure(figsize=(10, 5))\n",
    "plt.plot(range(1, len(cumulative_variance) + 1), cumulative_variance, color='royalblue', lw=2)\n",
    "plt.axhline(y=0.90, color='red', linestyle='--', label=f'90% Variance ({n_components_90} components)')\n",
    "plt.axhline(y=0.95, color='forestgreen', linestyle='--', label=f'95% Variance ({n_components_95} components)')\n",
    "plt.title(\"Cumulative Explained Variance Ratio by PCA Components\", fontsize=14)\n",
    "plt.xlabel(\"Number of Components\")\n",
    "plt.ylabel(\"Cumulative Explained Variance\")\n",
    "plt.legend(loc='lower right')\n",
    "plt.grid(True, linestyle='--', alpha=0.5)\n",
    "plt.tight_layout()\n",
    "plt.savefig(os.path.join(PLOT_DIR, \"01_pca_variance_plot.png\"), dpi=150)\n",
    "plt.show()\n",
    "\n",
    "print(f\"Number of components to preserve 90% variance: {n_components_90}\")\n",
    "print(f\"Number of components to preserve 95% variance: {n_components_95}\")\n",
    "\n",
    "# Re-fit PCA targeting 95% variance\n",
    "n_components = n_components_95\n",
    "pca = PCA(n_components=n_components, random_state=42)\n",
    "X_train_pca = pca.fit_transform(X_train_preprocessed)\n",
    "X_test_pca = pca.transform(X_test_preprocessed)\n",
    "\n",
    "print(f\"\\nPCA transformation complete. Features reduced from {X_train_preprocessed.shape[1]} to {X_train_pca.shape[1]}.\")\n",
    "\n",
    "# Visualize 2D projection scatter plot\n",
    "plt.figure(figsize=(10, 8))\n",
    "scatter = plt.scatter(X_train_pca[:, 0], X_train_pca[:, 1], c=y_train, cmap='tab10', alpha=0.6, s=15)\n",
    "plt.colorbar(scatter, ticks=range(10), label=\"Class ID\").set_ticklabels(class_names)\n",
    "plt.title(\"2D Projection of Fashion-MNIST using Top 2 Principal Components\", fontsize=14)\n",
    "plt.xlabel(\"First Principal Component\")\n",
    "plt.ylabel(\"Second Principal Component\")\n",
    "plt.grid(True, linestyle='--', alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig(os.path.join(PLOT_DIR, \"01_pca_2d_scatter.png\"), dpi=150)\n",
    "plt.show()\n",
    "\n",
    "# Plot top 10 Eigenimages\n",
    "fig, axes = plt.subplots(2, 5, figsize=(12, 6))\n",
    "axes = axes.ravel()\n",
    "for idx in range(10):\n",
    "    eigenimage = pca.components_[idx].reshape(14, 14)\n",
    "    axes[idx].imshow(eigenimage, cmap='coolwarm')\n",
    "    axes[idx].set_title(f\"PC {idx+1}\", fontsize=10)\n",
    "    axes[idx].axis('off')\n",
    "plt.suptitle(\"Top 10 Eigenimages (Principal Components)\", fontsize=14, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig(os.path.join(PLOT_DIR, \"01_pca_eigenimages.png\"), dpi=150)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "tuning_title",
   "metadata": {},
   "source": [
    "## 5. Model Training & Hyperparameter Tuning\n",
    "\n",
    "We define candidate parameter grids and run parallelized `GridSearchCV` to locate optimal configurations for both our **Support Vector Classifier (SVC)** and **k-Nearest Neighbors (kNN)** models."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "tuning_execution",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Support Vector Classifier (SVC) Grid Search\n",
    "print(\"Tuning Support Vector Classifier (SVC)...\")\n",
    "svc_param_grid = {\n",
    "    'C': [0.1, 1, 10],\n",
    "    'gamma': ['scale', 0.01, 0.001],\n",
    "    'kernel': ['rbf']\n",
    "}\n",
    "svc_grid = GridSearchCV(SVC(random_state=42), svc_param_grid, cv=3, n_jobs=-1, scoring='accuracy')\n",
    "start_time = time.time()\n",
    "svc_grid.fit(X_train_pca, y_train)\n",
    "svc_time = time.time() - start_time\n",
    "print(f\"SVC Best Params: {svc_grid.best_params_}\")\n",
    "print(f\"SVC Best Cross-Val Accuracy: {svc_grid.best_score_:.4f}\")\n",
    "print(f\"SVC Tuning Time: {svc_time:.2f} seconds\")\n",
    "\n",
    "# 2. k-Nearest Neighbors (kNN) Grid Search\n",
    "print(\"\\nTuning k-Nearest Neighbors (kNN)...\")\n",
    "knn_param_grid = {\n",
    "    'n_neighbors': [3, 5, 7, 9],\n",
    "    'weights': ['uniform', 'distance'],\n",
    "    'metric': ['euclidean', 'manhattan']\n",
    "}\n",
    "knn_grid = GridSearchCV(KNeighborsClassifier(), knn_param_grid, cv=3, n_jobs=-1, scoring='accuracy')\n",
    "start_time = time.time()\n",
    "knn_grid.fit(X_train_pca, y_train)\n",
    "knn_time = time.time() - start_time\n",
    "print(f\"kNN Best Params: {knn_grid.best_params_}\")\n",
    "print(f\"kNN Best Cross-Val Accuracy: {knn_grid.best_score_:.4f}\")\n",
    "print(f\"kNN Tuning Time: {knn_time:.2f} seconds\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "evaluation_title",
   "metadata": {},
   "source": [
    "## 6. Model Evaluation & Comparison\n",
    "\n",
    "We evaluate our best estimators on our unseen test split. We inspect precision, recall, and F1 metrics per product category and draw comparative metrics."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "evaluation_execution",
   "metadata": {},
   "outputs": [],
   "source": [
    "best_svc = svc_grid.best_estimator_\n",
    "best_knn = knn_grid.best_estimator_\n",
    "\n",
    "# Predict on test set\n",
    "start_eval = time.time()\n",
    "svc_preds = best_svc.predict(X_test_pca)\n",
    "svc_eval_time = time.time() - start_eval\n",
    "\n",
    "start_eval = time.time()\n",
    "knn_preds = best_knn.predict(X_test_pca)\n",
    "knn_eval_time = time.time() - start_eval\n",
    "\n",
    "svc_acc = accuracy_score(y_test, svc_preds)\n",
    "svc_f1 = f1_score(y_test, svc_preds, average='weighted')\n",
    "knn_acc = accuracy_score(y_test, knn_preds)\n",
    "knn_f1 = f1_score(y_test, knn_preds, average='weighted')\n",
    "\n",
    "print(\"=\"*60)\n",
    "print(\"SUPPORT VECTOR CLASSIFIER (SVC) TEST EVALUATION\")\n",
    "print(\"=\"*60)\n",
    "print(classification_report(y_test, svc_preds, target_names=class_names))\n",
    "\n",
    "print(\"=\"*60)\n",
    "print(\"k-NEAREST NEIGHBORS (kNN) TEST EVALUATION\")\n",
    "print(\"=\"*60)\n",
    "print(classification_report(y_test, knn_preds, target_names=class_names))\n",
    "\n",
    "# Plot Confusion Matrices\n",
    "fig, axes = plt.subplots(1, 2, figsize=(16, 7))\n",
    "\n",
    "ConfusionMatrixDisplay.from_predictions(\n",
    "    y_test, svc_preds, display_labels=class_names, \n",
    "    cmap='Blues', ax=axes[0], xticks_rotation=45\n",
    ")\n",
    "axes[0].set_title(f\"SVC Confusion Matrix (Acc: {svc_acc:.4f})\")\n",
    "\n",
    "ConfusionMatrixDisplay.from_predictions(\n",
    "    y_test, knn_preds, display_labels=class_names, \n",
    "    cmap='Greens', ax=axes[1], xticks_rotation=45\n",
    ")\n",
    "axes[1].set_title(f\"kNN Confusion Matrix (Acc: {knn_acc:.4f})\")\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig(os.path.join(PLOT_DIR, \"01_model_confusion_matrices.png\"), dpi=150)\n",
    "plt.show()\n",
    "\n",
    "# Plot Performance & Training time comparison side-by-side\n",
    "metrics_df = pd.DataFrame({\n",
    "    'Model': ['SVC', 'kNN'],\n",
    "    'Accuracy': [svc_acc, knn_acc],\n",
    "    'Weighted F1-Score': [svc_f1, knn_f1],\n",
    "    'Tuning Time (s)': [svc_time, knn_time]\n",
    "})\n",
    "\n",
    "fig, ax1 = plt.subplots(figsize=(8, 5))\n",
    "ax2 = ax1.twinx()\n",
    "\n",
    "width = 0.25\n",
    "ind = np.arange(2)\n",
    "\n",
    "rects1 = ax1.bar(ind - width/2, metrics_df['Accuracy'], width, label='Accuracy', color='royalblue')\n",
    "rects2 = ax1.bar(ind + width/2, metrics_df['Weighted F1-Score'], width, label='F1-Score', color='cornflowerblue')\n",
    "rects3 = ax2.bar(ind + width*1.5, metrics_df['Tuning Time (s)'], width, label='Tuning Time (s)', color='salmon', alpha=0.8)\n",
    "\n",
    "ax1.set_ylabel('Score', color='blue')\n",
    "ax2.set_ylabel('Time (seconds)', color='red')\n",
    "ax1.set_xticks(ind + width/2)\n",
    "ax1.set_xticklabels(metrics_df['Model'])\n",
    "ax1.set_ylim(0, 1.05)\n",
    "ax1.set_title(\"Performance & Computational Efficiency Comparison\")\n",
    "\n",
    "lines1, labels1 = ax1.get_legend_handles_labels()\n",
    "lines2, labels2 = ax2.get_legend_handles_labels()\n",
    "ax1.legend(lines1 + lines2, labels1 + labels2, loc='lower left')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig(os.path.join(PLOT_DIR, \"01_model_performance_comparison.png\"), dpi=150)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "save_title",
   "metadata": {},
   "source": [
    "## 7. Model Serialization\n",
    "\n",
    "We save our pipeline components (the best classifier, the PCA transformer, and meta configurations) as a single serialized joblib artifact for downstream predictions."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "save_execution",
   "metadata": {},
   "outputs": [],
   "source": [
    "MODELS_DIR = \"models\"\n",
    "os.makedirs(MODELS_DIR, exist_ok=True)\n",
    "\n",
    "best_model_obj = best_svc if svc_acc >= knn_acc else best_knn\n",
    "best_model_name = \"SVC\" if svc_acc >= knn_acc else \"kNN\"\n",
    "\n",
    "payload = {\n",
    "    'best_model': best_model_obj,\n",
    "    'best_model_name': best_model_name,\n",
    "    'pca_transformer': pca,\n",
    "    'class_names': class_names,\n",
    "    'target_resolution': (14, 14),\n",
    "    'metrics': {\n",
    "        'svc_accuracy': svc_acc,\n",
    "        'svc_f1': svc_f1,\n",
    "        'knn_accuracy': knn_acc,\n",
    "        'knn_f1': knn_f1\n",
    "    }\n",
    "}\n",
    "\n",
    "joblib.dump(payload, os.path.join(MODELS_DIR, \"fashion_classifier_pipeline.joblib\"))\n",
    "print(f\"Best model ({best_model_name}) and preprocessing/PCA payload successfully saved to models/fashion_classifier_pipeline.joblib\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

with open("project3_fashion_image_classifier/01_image_classification_pipeline.ipynb", "w") as f:
    json.dump(notebook, f, indent=1)
print("01_image_classification_pipeline.ipynb written successfully!")
